name: Deploy to Azure
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.20'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        # app-name: 'aspnode-rag-dev-fc-008'  Pia
        # app-name: 'app-ragfront-dev-frc-002' Sergio
        app-name: 'aspnode-rag-dev-fc-008'
        # publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} Pia
        # publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_SERGIO }} Sergio
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./dist
